apiVersion: 1

datasources:
  - name: Gameservers
    type: influxdb
    access: proxy
    url: http://hyperbytedb:8086
    database: gameservers
    jsonData:
      version: InfluxQL
    editable: true

  - name: Gameservers (default_high)
    type: influxdb
    access: proxy
    url: http://hyperbytedb:8086
    database: gameservers
    jsonData:
      version: InfluxQL
      retentionPolicy: default_high
    editable: true
