apiVersion: 1

datasources:
  - name: Flight Tracking
    type: influxdb
    access: proxy
    url: http://hyperbytedb:8086
    database: flight_tracking
    editable: true

  - name: Marine Tracking
    type: influxdb
    access: proxy
    url: http://hyperbytedb:8086
    database: marine_tracking
    editable: true

  - name: Satellite Tracking
    type: influxdb
    access: proxy
    url: http://hyperbytedb:8086
    database: n2yo
    editable: true

  - name: Energy Grid
    type: influxdb
    access: proxy
    url: http://hyperbytedb:8086
    database: energy_grid
    editable: true

  - name: Gameservers
    type: influxdb
    access: proxy
    url: http://hyperbytedb:8086
    database: gameservers
    editable: true
